version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: admission_bppk_db
    environment:
      POSTGRES_DB: admission_bppk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - admission_network

volumes:
  postgres_data:

networks:
  admission_network:
    driver: bridge
